/* Generated By:JavaCC: Do not edit this line. compiladoraulaTreeConstants.java Version 5.0 */
package parser;

public interface compiladoraulaTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTID = 1;
  public int JJTSENTENCAS = 2;
  public int JJTDECLARACAOVARIAVEL = 3;
  public int JJTTIPODADO = 4;
  public int JJTVALOR = 5;
  public int JJTFUNCAOESCREVER = 6;
  public int JJTFUNCAOLER = 7;
  public int JJTFUNCAOATRIBUICAO = 8;
  public int JJTOPERADORSIMPLES = 9;
  public int JJTOPERADORPARENTESES = 10;
  public int JJTOPERADORARITMETICO = 11;
  public int JJTFUNCAOSE = 12;
  public int JJTCONDICAO = 13;
  public int JJTCONDICAOSIMPLES = 14;
  public int JJTOPLOGICO = 15;
  public int JJTOPRELACIONAL = 16;
  public int JJTFUNCAOSELECIONE = 17;
  public int JJTFUNCAOPARA = 18;
  public int JJTFUNCAOENQUANTO = 19;
  public int JJTFUNCAOFACA = 20;


  public String[] jjtNodeName = {
    "main",
    "id",
    "sentencas",
    "declaracaoVariavel",
    "tipoDado",
    "valor",
    "funcaoEscrever",
    "funcaoLer",
    "funcaoAtribuicao",
    "operadorSimples",
    "operadorParenteses",
    "operadorAritmetico",
    "funcaoSE",
    "condicao",
    "condicaoSimples",
    "opLogico",
    "opRelacional",
    "funcaoSelecione",
    "funcaoPara",
    "funcaoEnquanto",
    "funcaoFaca",
  };
}
/* JavaCC - OriginalChecksum=28f02f73d1cbef72340df38e15b3fd07 (do not edit this line) */
